create table if not exists public.catalogue_partages (
  revendeur_id uuid primary key references public.profiles(id) on delete cascade,
  token uuid not null unique default gen_random_uuid(),
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.demandes_catalogue (
  id bigint generated by default as identity primary key,
  revendeur_id uuid not null references public.profiles(id) on delete restrict,
  nom_client text not null check (char_length(btrim(nom_client)) between 2 and 120),
  telephone text not null check (char_length(btrim(telephone)) between 6 and 30),
  note text check (note is null or char_length(note) <= 1000),
  statut text not null default 'nouvelle' check (statut in ('nouvelle', 'en_cours', 'convertie', 'archivee')),
  commande_id bigint references public.commandes(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.demande_catalogue_articles (
  id bigint generated by default as identity primary key,
  demande_id bigint not null references public.demandes_catalogue(id) on delete cascade,
  modele_stock_id bigint not null references public.modeles_stock(id) on delete restrict,
  quantite integer not null default 1 check (quantite between 1 and 20),
  pointure text check (pointure is null or char_length(btrim(pointure)) <= 40),
  couleur text check (couleur is null or char_length(btrim(couleur)) <= 80),
  position integer not null default 1 check (position > 0),
  created_at timestamptz not null default now(),
  unique (demande_id, modele_stock_id)
);

create index if not exists idx_demandes_catalogue_revendeur
on public.demandes_catalogue(revendeur_id, created_at desc);

create index if not exists idx_demande_catalogue_articles_demande
on public.demande_catalogue_articles(demande_id, position);

alter table public.notifications
add column if not exists demande_catalogue_id bigint references public.demandes_catalogue(id) on delete cascade;

drop trigger if exists catalogue_partages_updated_at on public.catalogue_partages;
create trigger catalogue_partages_updated_at
before update on public.catalogue_partages
for each row execute function public.update_updated_at();

drop trigger if exists demandes_catalogue_updated_at on public.demandes_catalogue;
create trigger demandes_catalogue_updated_at
before update on public.demandes_catalogue
for each row execute function public.update_updated_at();

alter table public.catalogue_partages enable row level security;
alter table public.demandes_catalogue enable row level security;
alter table public.demande_catalogue_articles enable row level security;

drop policy if exists catalogue_partages_select on public.catalogue_partages;
create policy catalogue_partages_select on public.catalogue_partages
for select to authenticated
using (revendeur_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists demandes_catalogue_select on public.demandes_catalogue;
create policy demandes_catalogue_select on public.demandes_catalogue
for select to authenticated
using (revendeur_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists demandes_catalogue_update on public.demandes_catalogue;
create policy demandes_catalogue_update on public.demandes_catalogue
for update to authenticated
using (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
with check (
  (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
  and (
    commande_id is null
    or exists (
      select 1 from public.commandes
      where commandes.id = demandes_catalogue.commande_id
        and (commandes.revendeur_id = auth.uid() or public.current_user_role() = 'admin')
    )
  )
);

drop policy if exists demande_catalogue_articles_select on public.demande_catalogue_articles;
create policy demande_catalogue_articles_select on public.demande_catalogue_articles
for select to authenticated
using (
  exists (
    select 1
    from public.demandes_catalogue
    where demandes_catalogue.id = demande_catalogue_articles.demande_id
      and (demandes_catalogue.revendeur_id = auth.uid() or public.current_user_role() = 'admin')
  )
);

grant select on public.catalogue_partages to authenticated;
grant select, update on public.demandes_catalogue to authenticated;
grant select on public.demande_catalogue_articles to authenticated;

create or replace function public.get_or_create_catalogue_token()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  share_token uuid;
begin
  if auth.uid() is null or not public.is_manager() then
    raise exception 'Accès refusé';
  end if;

  insert into public.catalogue_partages (revendeur_id, actif)
  values (auth.uid(), true)
  on conflict (revendeur_id) do update
  set actif = true,
      updated_at = now()
  returning token into share_token;

  return share_token;
end;
$$;

create or replace function public.rotate_catalogue_token()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  share_token uuid;
begin
  if auth.uid() is null or not public.is_manager() then
    raise exception 'Accès refusé';
  end if;

  insert into public.catalogue_partages (revendeur_id, token, actif)
  values (auth.uid(), gen_random_uuid(), true)
  on conflict (revendeur_id) do update
  set token = gen_random_uuid(),
      actif = true,
      updated_at = now()
  returning token into share_token;

  return share_token;
end;
$$;

create or replace function public.get_catalogue_public(p_token uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  order_owner uuid;
  catalog jsonb;
begin
  select revendeur_id into order_owner
  from public.catalogue_partages
  where token = p_token and actif = true;

  if order_owner is null then
    return null;
  end if;

  select jsonb_build_object(
    'entreprise', 'EHE',
    'modeles', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', modeles_stock.id,
          'nom', modeles_stock.nom,
          'reference', modeles_stock.reference,
          'description', modeles_stock.description,
          'photo_path', modeles_stock.photo_path
        ) order by modeles_stock.created_at desc
      ) filter (where modeles_stock.id is not null),
      '[]'::jsonb
    )
  ) into catalog
  from public.modeles_stock
  where revendeur_id = order_owner and is_active = true;

  return catalog;
end;
$$;

create or replace function public.submit_demande_catalogue(
  p_token uuid,
  p_nom_client text,
  p_telephone text,
  p_note text,
  p_articles jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  order_owner uuid;
  created_request_id bigint;
  request_line jsonb;
  request_position bigint;
  model_id bigint;
  requested_quantity integer;
  line_count integer;
begin
  select revendeur_id into order_owner
  from public.catalogue_partages
  where token = p_token and actif = true;

  if order_owner is null then
    raise exception 'Ce lien de catalogue est invalide ou désactivé';
  end if;

  if char_length(btrim(coalesce(p_nom_client, ''))) < 2
    or char_length(btrim(coalesce(p_telephone, ''))) < 6 then
    raise exception 'Le nom et le téléphone sont obligatoires';
  end if;

  if jsonb_typeof(p_articles) is distinct from 'array' then
    raise exception 'Le panier est invalide';
  end if;

  line_count := jsonb_array_length(p_articles);
  if line_count < 1 or line_count > 50 then
    raise exception 'Le panier doit contenir entre 1 et 50 modèles';
  end if;

  if (
    select count(distinct (value ->> 'modele_stock_id')::bigint)
    from jsonb_array_elements(p_articles)
  ) <> line_count then
    raise exception 'Un même modèle ne peut apparaître qu’une fois dans le panier';
  end if;

  for request_line, request_position in
    select value, ordinality
    from jsonb_array_elements(p_articles) with ordinality
  loop
    model_id := (request_line ->> 'modele_stock_id')::bigint;
    requested_quantity := (request_line ->> 'quantite')::integer;

    if requested_quantity < 1 or requested_quantity > 20 then
      raise exception 'La quantité de la ligne % est invalide', request_position;
    end if;

    if not exists (
      select 1 from public.modeles_stock
      where id = model_id and revendeur_id = order_owner and is_active = true
    ) then
      raise exception 'Le modèle de la ligne % n’est plus disponible', request_position;
    end if;
  end loop;

  insert into public.demandes_catalogue (revendeur_id, nom_client, telephone, note)
  values (
    order_owner,
    btrim(p_nom_client),
    btrim(p_telephone),
    nullif(btrim(coalesce(p_note, '')), '')
  )
  returning id into created_request_id;

  for request_line, request_position in
    select value, ordinality
    from jsonb_array_elements(p_articles) with ordinality
  loop
    insert into public.demande_catalogue_articles (
      demande_id,
      modele_stock_id,
      quantite,
      pointure,
      couleur,
      position
    ) values (
      created_request_id,
      (request_line ->> 'modele_stock_id')::bigint,
      (request_line ->> 'quantite')::integer,
      nullif(btrim(coalesce(request_line ->> 'pointure', '')), ''),
      nullif(btrim(coalesce(request_line ->> 'couleur', '')), ''),
      request_position
    );
  end loop;

  insert into public.notifications (user_id, demande_catalogue_id, message)
  values (
    order_owner,
    created_request_id,
    'Nouvelle demande de ' || btrim(p_nom_client) || ' depuis le catalogue (' || line_count || ' modèle' || case when line_count > 1 then 's' else '' end || ').'
  );

  return created_request_id;
end;
$$;

update storage.buckets
set public = true
where id = 'modele-photos';

revoke execute on function public.get_or_create_catalogue_token() from public, anon;
grant execute on function public.get_or_create_catalogue_token() to authenticated;
revoke execute on function public.rotate_catalogue_token() from public, anon;
grant execute on function public.rotate_catalogue_token() to authenticated;
revoke execute on function public.get_catalogue_public(uuid) from public;
grant execute on function public.get_catalogue_public(uuid) to anon, authenticated;
revoke execute on function public.submit_demande_catalogue(uuid, text, text, text, jsonb) from public;
grant execute on function public.submit_demande_catalogue(uuid, text, text, text, jsonb) to anon, authenticated;
