create table if not exists public.commande_messages (
  id bigint generated by default as identity primary key,
  commande_id bigint not null references public.commandes(id) on delete cascade,
  auteur_id uuid references public.profiles(id) on delete set null,
  auteur_nom text not null,
  auteur_role text not null check (auteur_role in ('revendeur', 'cordonnier', 'admin')),
  contenu text not null check (char_length(btrim(contenu)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists idx_commande_messages_commande_created_at
on public.commande_messages(commande_id, created_at);

create or replace function public.prepare_commande_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  sender_profile public.profiles%rowtype;
begin
  if auth.uid() is null or not public.can_access_commande(new.commande_id) then
    raise exception 'Accès refusé à cette conversation';
  end if;

  select * into sender_profile
  from public.profiles
  where id = auth.uid() and is_active = true;

  if not found then
    raise exception 'Profil utilisateur invalide';
  end if;

  new.auteur_id := auth.uid();
  new.auteur_nom := sender_profile.nom;
  new.auteur_role := sender_profile.role;
  new.contenu := btrim(new.contenu);
  return new;
end;
$$;

drop trigger if exists prepare_commande_message on public.commande_messages;
create trigger prepare_commande_message
before insert on public.commande_messages
for each row execute function public.prepare_commande_message();

create or replace function public.notify_commande_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.commandes%rowtype;
begin
  select * into current_order
  from public.commandes
  where id = new.commande_id;

  insert into public.notifications (user_id, commande_id, message)
  select recipient_id, new.commande_id,
    'Nouveau message de ' || new.auteur_nom || ' sur la commande ' || current_order.numero_commande || '.'
  from (
    select current_order.revendeur_id as recipient_id
    union
    select current_order.cordonnier_id as recipient_id
  ) recipients
  where recipient_id is not null and recipient_id is distinct from new.auteur_id;

  return new;
end;
$$;

drop trigger if exists notify_commande_message on public.commande_messages;
create trigger notify_commande_message
after insert on public.commande_messages
for each row execute function public.notify_commande_message();

alter table public.commande_messages enable row level security;

drop policy if exists commande_messages_select on public.commande_messages;
create policy commande_messages_select on public.commande_messages
for select to authenticated
using (public.can_access_commande(commande_id));

drop policy if exists commande_messages_insert on public.commande_messages;
create policy commande_messages_insert on public.commande_messages
for insert to authenticated
with check (
  auteur_id = auth.uid()
  and public.can_access_commande(commande_id)
);

grant select, insert on public.commande_messages to authenticated;
grant usage, select on sequence public.commande_messages_id_seq to authenticated;

revoke execute on function public.prepare_commande_message() from public, anon, authenticated;
revoke execute on function public.notify_commande_message() from public, anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'commande_messages'
  ) then
    alter publication supabase_realtime add table public.commande_messages;
  end if;
end;
$$;
