create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nom text not null,
  email text unique not null,
  role text not null default 'cordonnier' check (role in ('revendeur', 'cordonnier', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  revendeur_id uuid not null default auth.uid() references public.profiles(id) on delete restrict,
  nom text not null,
  telephone text not null,
  email text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create sequence if not exists public.commande_numero_seq;

create table if not exists public.commandes (
  id bigint generated by default as identity primary key,
  numero_commande text unique,
  client_id bigint not null,
  revendeur_id uuid not null default auth.uid(),
  cordonnier_id uuid not null,
  modele text not null,
  pointure text not null,
  couleur text not null,
  matiere text not null,
  semelle text not null,
  quantite integer not null default 1 check (quantite > 0),
  statut text not null default 'en_attente' check (statut in ('en_attente', 'en_fabrication', 'prete', 'livree', 'annulee')),
  date_souhaitee date,
  date_creation timestamptz not null default now(),
  date_debut_fabrication timestamptz,
  date_fin timestamptz,
  observations text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commandes_client_id_fkey foreign key (client_id) references public.clients(id) on delete restrict,
  constraint commandes_revendeur_id_fkey foreign key (revendeur_id) references public.profiles(id) on delete restrict,
  constraint commandes_cordonnier_id_fkey foreign key (cordonnier_id) references public.profiles(id) on delete restrict
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  commande_id bigint not null references public.commandes(id) on delete cascade,
  type_photo text not null check (type_photo in ('modele', 'pied_gauche', 'pied_droit', 'autre')),
  storage_path text not null,
  file_name text not null,
  created_at timestamptz not null default now(),
  unique (commande_id, type_photo)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  commande_id bigint references public.commandes(id) on delete cascade,
  message text not null,
  lu boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.commande_statuts (
  id bigint generated by default as identity primary key,
  commande_id bigint not null references public.commandes(id) on delete cascade,
  user_id uuid,
  statut text not null check (statut in ('en_attente', 'en_fabrication', 'prete', 'livree', 'annulee')),
  commentaire text,
  created_at timestamptz not null default now(),
  constraint commande_statuts_user_id_fkey foreign key (user_id) references public.profiles(id) on delete set null
);

create index if not exists idx_clients_revendeur_id on public.clients(revendeur_id);
create index if not exists idx_commandes_client_id on public.commandes(client_id);
create index if not exists idx_commandes_revendeur_id on public.commandes(revendeur_id);
create index if not exists idx_commandes_cordonnier_id on public.commandes(cordonnier_id);
create index if not exists idx_commandes_statut on public.commandes(statut);
create index if not exists idx_photos_commande_id on public.photos(commande_id);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_lu on public.notifications(lu);
create index if not exists idx_commande_statuts_commande_id on public.commande_statuts(commande_id);

create or replace function public.update_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute function public.update_updated_at();

drop trigger if exists clients_updated_at on public.clients;
create trigger clients_updated_at before update on public.clients
for each row execute function public.update_updated_at();

drop trigger if exists commandes_updated_at on public.commandes;
create trigger commandes_updated_at before update on public.commandes
for each row execute function public.update_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  initial_role text;
begin
  if exists (select 1 from public.profiles where role in ('revendeur', 'admin')) then
    initial_role := 'cordonnier';
  else
    initial_role := 'revendeur';
  end if;

  insert into public.profiles (id, nom, email, role)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'nom', ''), split_part(new.email, '@', 1)),
    new.email,
    initial_role
  )
  on conflict (id) do update
  set nom = excluded.nom, email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid() and is_active = true;
$$;

create or replace function public.is_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('revendeur', 'admin'), false);
$$;

create or replace function public.can_access_commande(p_commande_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.commandes
    where id = p_commande_id
      and (
        revendeur_id = auth.uid()
        or cordonnier_id = auth.uid()
        or public.current_user_role() = 'admin'
      )
  );
$$;

create or replace function public.can_manage_commande(p_commande_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.commandes
    where id = p_commande_id
      and (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
  );
$$;

create or replace function public.set_commande_numero()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.numero_commande is null or new.numero_commande = '' then
    new.numero_commande := 'CMD-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('public.commande_numero_seq')::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists set_commande_numero on public.commandes;
create trigger set_commande_numero before insert on public.commandes
for each row execute function public.set_commande_numero();

create or replace function public.add_initial_commande_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.commande_statuts (commande_id, user_id, statut, commentaire)
  values (new.id, auth.uid(), new.statut, 'Commande créée');
  return new;
end;
$$;

drop trigger if exists add_initial_commande_status on public.commandes;
create trigger add_initial_commande_status after insert on public.commandes
for each row execute function public.add_initial_commande_status();

create or replace function public.change_commande_status(p_commande_id bigint, p_nouveau_statut text)
returns public.commandes
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.commandes%rowtype;
  updated_order public.commandes%rowtype;
  current_role text;
  transition_allowed boolean := false;
begin
  if p_nouveau_statut not in ('en_attente', 'en_fabrication', 'prete', 'livree', 'annulee') then
    raise exception 'Statut invalide';
  end if;

  select * into current_order
  from public.commandes
  where id = p_commande_id
  for update;

  if not found then
    raise exception 'Commande introuvable';
  end if;

  current_role := public.current_user_role();

  if current_role = 'cordonnier' then
    if current_order.cordonnier_id is distinct from auth.uid() then
      raise exception 'Cette commande ne vous est pas attribuée';
    end if;
    transition_allowed :=
      (current_order.statut = 'en_attente' and p_nouveau_statut = 'en_fabrication')
      or (current_order.statut = 'en_fabrication' and p_nouveau_statut = 'prete');
  elsif current_role = 'revendeur' then
    if current_order.revendeur_id is distinct from auth.uid() then
      raise exception 'Accès refusé';
    end if;
    transition_allowed :=
      (current_order.statut = 'en_attente' and p_nouveau_statut = 'annulee')
      or (current_order.statut = 'prete' and p_nouveau_statut = 'livree');
  elsif current_role = 'admin' then
    transition_allowed := true;
  else
    raise exception 'Accès refusé';
  end if;

  if not transition_allowed then
    raise exception 'Transition de statut non autorisée';
  end if;

  update public.commandes
  set statut = p_nouveau_statut,
      date_debut_fabrication = case when p_nouveau_statut = 'en_fabrication' then coalesce(date_debut_fabrication, now()) else date_debut_fabrication end,
      date_fin = case when p_nouveau_statut in ('prete', 'livree', 'annulee') then now() else date_fin end
  where id = p_commande_id
  returning * into updated_order;

  insert into public.commande_statuts (commande_id, user_id, statut)
  values (p_commande_id, auth.uid(), p_nouveau_statut);

  if p_nouveau_statut = 'prete' then
    insert into public.notifications (user_id, commande_id, message)
    values (current_order.revendeur_id, p_commande_id, 'La commande ' || current_order.numero_commande || ' est prête.');
  end if;

  return updated_order;
end;
$$;

alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.commandes enable row level security;
alter table public.photos enable row level security;
alter table public.notifications enable row level security;
alter table public.commande_statuts enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_manager());

drop policy if exists clients_select on public.clients;
create policy clients_select on public.clients
for select to authenticated
using (revendeur_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists clients_insert on public.clients;
create policy clients_insert on public.clients
for insert to authenticated
with check (public.is_manager() and (revendeur_id = auth.uid() or public.current_user_role() = 'admin'));

drop policy if exists clients_update on public.clients;
create policy clients_update on public.clients
for update to authenticated
using (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
with check (revendeur_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists commandes_select on public.commandes;
create policy commandes_select on public.commandes
for select to authenticated
using (
  revendeur_id = auth.uid()
  or cordonnier_id = auth.uid()
  or public.current_user_role() = 'admin'
);

drop policy if exists commandes_insert on public.commandes;
create policy commandes_insert on public.commandes
for insert to authenticated
with check (
  public.is_manager()
  and (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
  and exists (
    select 1 from public.clients
    where id = commandes.client_id and (clients.revendeur_id = auth.uid() or public.current_user_role() = 'admin')
  )
  and exists (
    select 1 from public.profiles
    where id = commandes.cordonnier_id and role = 'cordonnier' and is_active = true
  )
);

drop policy if exists photos_select on public.photos;
create policy photos_select on public.photos
for select to authenticated
using (public.can_access_commande(commande_id));

drop policy if exists photos_insert on public.photos;
create policy photos_insert on public.photos
for insert to authenticated
with check (public.can_manage_commande(commande_id));

drop policy if exists notifications_select on public.notifications;
create policy notifications_select on public.notifications
for select to authenticated
using (user_id = auth.uid());

drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists commande_statuts_select on public.commande_statuts;
create policy commande_statuts_select on public.commande_statuts
for select to authenticated
using (public.can_access_commande(commande_id));

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update on public.clients to authenticated;
grant select, insert on public.commandes to authenticated;
grant select, insert on public.photos to authenticated;
grant select, update on public.notifications to authenticated;
grant select on public.commande_statuts to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_manager() to authenticated;
grant execute on function public.can_access_commande(bigint) to authenticated;
grant execute on function public.can_manage_commande(bigint) to authenticated;
grant execute on function public.change_commande_status(bigint, text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'commande-photos',
  'commande-photos',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists commande_photos_select on storage.objects;
create policy commande_photos_select on storage.objects
for select to authenticated
using (
  bucket_id = 'commande-photos'
  and public.can_access_commande(
    case
      when (storage.foldername(name))[1] ~ '^[0-9]+$' then ((storage.foldername(name))[1])::bigint
      else null
    end
  )
);

drop policy if exists commande_photos_insert on storage.objects;
create policy commande_photos_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'commande-photos'
  and public.can_manage_commande(
    case
      when (storage.foldername(name))[1] ~ '^[0-9]+$' then ((storage.foldername(name))[1])::bigint
      else null
    end
  )
);

drop policy if exists commande_photos_delete on storage.objects;
create policy commande_photos_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'commande-photos'
  and public.can_manage_commande(
    case
      when (storage.foldername(name))[1] ~ '^[0-9]+$' then ((storage.foldername(name))[1])::bigint
      else null
    end
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end;
$$;
