create table if not exists public.commande_paiements (
  id bigint generated by default as identity primary key,
  commande_id bigint not null references public.commandes(id) on delete cascade,
  revendeur_id uuid not null references public.profiles(id) on delete restrict,
  montant numeric(14, 2) not null check (montant > 0),
  mode_paiement text not null check (mode_paiement in ('especes', 'mobile_money', 'virement', 'carte', 'autre')),
  reference text,
  note text,
  date_paiement timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (reference is null or char_length(reference) <= 120),
  check (note is null or char_length(note) <= 300)
);

create index if not exists idx_commande_paiements_commande
on public.commande_paiements(commande_id, date_paiement desc);

create index if not exists idx_commande_paiements_revendeur
on public.commande_paiements(revendeur_id);

alter table public.commande_paiements enable row level security;

drop policy if exists commande_paiements_select on public.commande_paiements;
create policy commande_paiements_select on public.commande_paiements
for select to authenticated
using (revendeur_id = auth.uid() or public.current_user_role() = 'admin');

grant select on public.commande_paiements to authenticated;
revoke insert, update, delete on public.commande_paiements from authenticated;

create or replace function public.validate_commande_sale_against_payments()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  paid_total numeric(14, 2);
begin
  select coalesce(sum(montant), 0) into paid_total
  from public.commande_paiements
  where commande_id = new.commande_id;

  if new.prix_vente < paid_total then
    raise exception 'Le prix de vente ne peut pas être inférieur au montant déjà encaissé';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_commande_sale_against_payments on public.commande_comptabilite;
create trigger validate_commande_sale_against_payments
before insert or update of prix_vente on public.commande_comptabilite
for each row execute function public.validate_commande_sale_against_payments();

create or replace function public.save_commande_paiement(
  p_commande_id bigint,
  p_montant numeric,
  p_mode_paiement text,
  p_reference text default null,
  p_note text default null,
  p_date_paiement timestamptz default now()
)
returns public.commande_paiements
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.commandes%rowtype;
  sale_total numeric(14, 2);
  paid_total numeric(14, 2);
  saved_payment public.commande_paiements%rowtype;
begin
  select * into current_order
  from public.commandes
  where id = p_commande_id
  for update;

  if not found then
    raise exception 'Commande introuvable';
  end if;

  if auth.uid() is null
    or not public.is_manager()
    or (public.current_user_role() <> 'admin' and current_order.revendeur_id is distinct from auth.uid()) then
    raise exception 'Accès refusé';
  end if;

  select prix_vente into sale_total
  from public.commande_comptabilite
  where commande_id = p_commande_id;

  if sale_total is null then
    raise exception 'Enregistrez d’abord les prix de vente de cette commande';
  end if;

  if p_montant is null or p_montant <= 0 then
    raise exception 'Le montant du paiement doit être supérieur à zéro';
  end if;

  if p_mode_paiement not in ('especes', 'mobile_money', 'virement', 'carte', 'autre') then
    raise exception 'Mode de paiement invalide';
  end if;

  select coalesce(sum(montant), 0) into paid_total
  from public.commande_paiements
  where commande_id = p_commande_id;

  if paid_total + p_montant > sale_total then
    raise exception 'Le paiement dépasse le reste à payer';
  end if;

  insert into public.commande_paiements (
    commande_id,
    revendeur_id,
    montant,
    mode_paiement,
    reference,
    note,
    date_paiement
  ) values (
    p_commande_id,
    current_order.revendeur_id,
    p_montant,
    p_mode_paiement,
    nullif(btrim(p_reference), ''),
    nullif(btrim(p_note), ''),
    coalesce(p_date_paiement, now())
  )
  returning * into saved_payment;

  return saved_payment;
end;
$$;

create or replace function public.delete_commande_paiement(p_paiement_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_payment public.commande_paiements%rowtype;
begin
  select * into current_payment
  from public.commande_paiements
  where id = p_paiement_id
  for update;

  if not found then
    raise exception 'Paiement introuvable';
  end if;

  if auth.uid() is null
    or not public.is_manager()
    or (public.current_user_role() <> 'admin' and current_payment.revendeur_id is distinct from auth.uid()) then
    raise exception 'Accès refusé';
  end if;

  delete from public.commande_paiements
  where id = p_paiement_id;
end;
$$;

revoke execute on function public.save_commande_paiement(bigint, numeric, text, text, text, timestamptz) from public, anon;
grant execute on function public.save_commande_paiement(bigint, numeric, text, text, text, timestamptz) to authenticated;
revoke execute on function public.delete_commande_paiement(bigint) from public, anon;
grant execute on function public.delete_commande_paiement(bigint) to authenticated;
revoke execute on function public.validate_commande_sale_against_payments() from public, anon, authenticated;
