create table if not exists public.commande_articles (
  id bigint generated by default as identity primary key,
  commande_id bigint not null references public.commandes(id) on delete cascade,
  modele_stock_id bigint references public.modeles_stock(id) on delete set null,
  modele text not null check (char_length(btrim(modele)) between 1 and 120),
  pointure text not null check (char_length(btrim(pointure)) between 1 and 40),
  couleur text not null check (char_length(btrim(couleur)) between 1 and 80),
  matiere text not null check (char_length(btrim(matiere)) between 1 and 120),
  semelle text not null check (char_length(btrim(semelle)) between 1 and 120),
  quantite integer not null default 1 check (quantite > 0),
  position integer not null default 1 check (position > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_commande_articles_commande
on public.commande_articles(commande_id, position);

create index if not exists idx_commande_articles_modele_stock
on public.commande_articles(modele_stock_id);

drop trigger if exists commande_articles_updated_at on public.commande_articles;
create trigger commande_articles_updated_at
before update on public.commande_articles
for each row execute function public.update_updated_at();

insert into public.commande_articles (
  commande_id,
  modele_stock_id,
  modele,
  pointure,
  couleur,
  matiere,
  semelle,
  quantite,
  position
)
select
  commandes.id,
  commandes.modele_stock_id,
  commandes.modele,
  commandes.pointure,
  commandes.couleur,
  commandes.matiere,
  commandes.semelle,
  commandes.quantite,
  1
from public.commandes
where not exists (
  select 1 from public.commande_articles
  where commande_articles.commande_id = commandes.id
);

alter table public.commande_articles enable row level security;

drop policy if exists commande_articles_select on public.commande_articles;
create policy commande_articles_select on public.commande_articles
for select to authenticated
using (public.can_access_commande(commande_id));

grant select on public.commande_articles to authenticated;

create or replace function public.create_commande_multi(
  p_client_id bigint,
  p_cordonnier_id uuid,
  p_date_souhaitee date,
  p_observations text,
  p_articles jsonb
)
returns public.commandes
language plpgsql
security definer
set search_path = public
as $$
declare
  created_order public.commandes%rowtype;
  order_owner uuid;
  first_article jsonb;
  article jsonb;
  article_position bigint;
  article_model_id bigint;
  article_quantity integer;
  total_quantity integer := 0;
  article_count integer;
begin
  if auth.uid() is null or not public.is_manager() then
    raise exception 'Accès refusé';
  end if;

  select revendeur_id into order_owner
  from public.clients
  where id = p_client_id
    and (revendeur_id = auth.uid() or public.current_user_role() = 'admin');

  if order_owner is null then
    raise exception 'Client invalide';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_cordonnier_id and role = 'cordonnier' and is_active = true
  ) then
    raise exception 'Cordonnier invalide';
  end if;

  if jsonb_typeof(p_articles) <> 'array' then
    raise exception 'Les articles de la commande sont invalides';
  end if;

  article_count := jsonb_array_length(p_articles);
  if article_count < 1 or article_count > 50 then
    raise exception 'Une commande doit contenir entre 1 et 50 lignes';
  end if;

  first_article := p_articles -> 0;

  for article, article_position in
    select value, ordinality
    from jsonb_array_elements(p_articles) with ordinality
  loop
    article_model_id := nullif(article ->> 'modele_stock_id', '')::bigint;
    article_quantity := (article ->> 'quantite')::integer;

    if nullif(btrim(article ->> 'modele'), '') is null
      or nullif(btrim(article ->> 'pointure'), '') is null
      or nullif(btrim(article ->> 'couleur'), '') is null
      or nullif(btrim(article ->> 'matiere'), '') is null
      or nullif(btrim(article ->> 'semelle'), '') is null
      or article_quantity < 1 then
      raise exception 'La ligne % contient des informations invalides', article_position;
    end if;

    if article_model_id is not null and not exists (
      select 1 from public.modeles_stock
      where id = article_model_id
        and (revendeur_id = order_owner or public.current_user_role() = 'admin')
    ) then
      raise exception 'Modèle de stock invalide à la ligne %', article_position;
    end if;

    total_quantity := total_quantity + article_quantity;
  end loop;

  insert into public.commandes (
    client_id,
    revendeur_id,
    cordonnier_id,
    modele_stock_id,
    modele,
    pointure,
    couleur,
    matiere,
    semelle,
    quantite,
    date_souhaitee,
    observations
  ) values (
    p_client_id,
    order_owner,
    p_cordonnier_id,
    nullif(first_article ->> 'modele_stock_id', '')::bigint,
    case when article_count = 1 then btrim(first_article ->> 'modele') else article_count || ' modèles' end,
    case when article_count = 1 then btrim(first_article ->> 'pointure') else 'Variées' end,
    case when article_count = 1 then btrim(first_article ->> 'couleur') else 'Variées' end,
    case when article_count = 1 then btrim(first_article ->> 'matiere') else 'Variées' end,
    case when article_count = 1 then btrim(first_article ->> 'semelle') else 'Variées' end,
    total_quantity,
    p_date_souhaitee,
    nullif(btrim(p_observations), '')
  ) returning * into created_order;

  for article, article_position in
    select value, ordinality
    from jsonb_array_elements(p_articles) with ordinality
  loop
    insert into public.commande_articles (
      commande_id,
      modele_stock_id,
      modele,
      pointure,
      couleur,
      matiere,
      semelle,
      quantite,
      position
    ) values (
      created_order.id,
      nullif(article ->> 'modele_stock_id', '')::bigint,
      btrim(article ->> 'modele'),
      btrim(article ->> 'pointure'),
      btrim(article ->> 'couleur'),
      btrim(article ->> 'matiere'),
      btrim(article ->> 'semelle'),
      (article ->> 'quantite')::integer,
      article_position
    );
  end loop;

  return created_order;
end;
$$;

create or replace function public.update_commande_details(
  p_commande_id bigint,
  p_details jsonb
)
returns public.commandes
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.commandes%rowtype;
  updated_order public.commandes%rowtype;
  requested_client_id bigint;
  requested_cordonnier_id uuid;
  articles jsonb;
  first_article jsonb;
  article jsonb;
  article_position bigint;
  article_model_id bigint;
  article_quantity integer;
  total_quantity integer := 0;
  article_count integer;
begin
  select * into current_order
  from public.commandes
  where id = p_commande_id
  for update;

  if not found then raise exception 'Commande introuvable'; end if;

  if not public.is_manager()
    or (public.current_user_role() <> 'admin' and current_order.revendeur_id is distinct from auth.uid()) then
    raise exception 'Accès refusé';
  end if;

  if current_order.statut <> 'en_attente' then
    raise exception 'Seule une commande en attente peut être corrigée';
  end if;

  requested_client_id := (p_details ->> 'client_id')::bigint;
  requested_cordonnier_id := (p_details ->> 'cordonnier_id')::uuid;
  articles := p_details -> 'articles';

  if jsonb_typeof(articles) <> 'array' then
    raise exception 'Les articles de la commande sont invalides';
  end if;

  article_count := jsonb_array_length(articles);
  if article_count < 1 or article_count > 50 then
    raise exception 'Une commande doit contenir entre 1 et 50 lignes';
  end if;

  if not exists (
    select 1 from public.clients
    where id = requested_client_id
      and (revendeur_id = current_order.revendeur_id or public.current_user_role() = 'admin')
  ) then raise exception 'Client invalide'; end if;

  if not exists (
    select 1 from public.profiles
    where id = requested_cordonnier_id and role = 'cordonnier' and is_active = true
  ) then raise exception 'Cordonnier invalide'; end if;

  first_article := articles -> 0;

  for article, article_position in
    select value, ordinality
    from jsonb_array_elements(articles) with ordinality
  loop
    article_model_id := nullif(article ->> 'modele_stock_id', '')::bigint;
    article_quantity := (article ->> 'quantite')::integer;

    if nullif(btrim(article ->> 'modele'), '') is null
      or nullif(btrim(article ->> 'pointure'), '') is null
      or nullif(btrim(article ->> 'couleur'), '') is null
      or nullif(btrim(article ->> 'matiere'), '') is null
      or nullif(btrim(article ->> 'semelle'), '') is null
      or article_quantity < 1 then
      raise exception 'La ligne % contient des informations invalides', article_position;
    end if;

    if article_model_id is not null and not exists (
      select 1 from public.modeles_stock
      where id = article_model_id
        and (revendeur_id = current_order.revendeur_id or public.current_user_role() = 'admin')
    ) then raise exception 'Modèle de stock invalide à la ligne %', article_position; end if;

    total_quantity := total_quantity + article_quantity;
  end loop;

  update public.commandes
  set client_id = requested_client_id,
      cordonnier_id = requested_cordonnier_id,
      modele_stock_id = nullif(first_article ->> 'modele_stock_id', '')::bigint,
      modele = case when article_count = 1 then btrim(first_article ->> 'modele') else article_count || ' modèles' end,
      pointure = case when article_count = 1 then btrim(first_article ->> 'pointure') else 'Variées' end,
      couleur = case when article_count = 1 then btrim(first_article ->> 'couleur') else 'Variées' end,
      matiere = case when article_count = 1 then btrim(first_article ->> 'matiere') else 'Variées' end,
      semelle = case when article_count = 1 then btrim(first_article ->> 'semelle') else 'Variées' end,
      quantite = total_quantity,
      date_souhaitee = nullif(p_details ->> 'date_souhaitee', '')::date,
      observations = nullif(btrim(p_details ->> 'observations'), '')
  where id = p_commande_id
  returning * into updated_order;

  delete from public.commande_articles where commande_id = p_commande_id;

  for article, article_position in
    select value, ordinality
    from jsonb_array_elements(articles) with ordinality
  loop
    insert into public.commande_articles (
      commande_id, modele_stock_id, modele, pointure, couleur, matiere, semelle, quantite, position
    ) values (
      p_commande_id,
      nullif(article ->> 'modele_stock_id', '')::bigint,
      btrim(article ->> 'modele'),
      btrim(article ->> 'pointure'),
      btrim(article ->> 'couleur'),
      btrim(article ->> 'matiere'),
      btrim(article ->> 'semelle'),
      (article ->> 'quantite')::integer,
      article_position
    );
  end loop;

  return updated_order;
end;
$$;

drop policy if exists modeles_stock_select on public.modeles_stock;
create policy modeles_stock_select on public.modeles_stock
for select to authenticated
using (
  revendeur_id = auth.uid()
  or public.current_user_role() = 'admin'
  or exists (
    select 1
    from public.commande_articles
    join public.commandes on commandes.id = commande_articles.commande_id
    where commande_articles.modele_stock_id = modeles_stock.id
      and commandes.cordonnier_id = auth.uid()
  )
);

create or replace function public.can_access_modele_photo(p_storage_path text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.modeles_stock
    where photo_path = p_storage_path
      and (
        revendeur_id = auth.uid()
        or public.current_user_role() = 'admin'
        or exists (
          select 1
          from public.commande_articles
          join public.commandes on commandes.id = commande_articles.commande_id
          where commande_articles.modele_stock_id = modeles_stock.id
            and commandes.cordonnier_id = auth.uid()
        )
      )
  );
$$;

revoke execute on function public.create_commande_multi(bigint, uuid, date, text, jsonb) from public, anon;
grant execute on function public.create_commande_multi(bigint, uuid, date, text, jsonb) to authenticated;
revoke execute on function public.update_commande_details(bigint, jsonb) from public, anon;
grant execute on function public.update_commande_details(bigint, jsonb) to authenticated;
revoke execute on function public.can_access_modele_photo(text) from public, anon;
grant execute on function public.can_access_modele_photo(text) to authenticated;
