create table if not exists public.modeles_stock (
  id bigint generated by default as identity primary key,
  revendeur_id uuid not null default auth.uid() references public.profiles(id) on delete restrict,
  nom text not null check (char_length(btrim(nom)) between 1 and 120),
  reference text,
  description text,
  photo_path text not null unique,
  file_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (reference is null or char_length(btrim(reference)) between 1 and 60),
  check (description is null or char_length(description) <= 1000)
);

create index if not exists idx_modeles_stock_revendeur
on public.modeles_stock(revendeur_id, created_at desc);

create unique index if not exists idx_modeles_stock_reference_unique
on public.modeles_stock(revendeur_id, lower(reference))
where reference is not null;

alter table public.commandes
add column if not exists modele_stock_id bigint references public.modeles_stock(id) on delete set null;

create index if not exists idx_commandes_modele_stock_id
on public.commandes(modele_stock_id);

drop trigger if exists modeles_stock_updated_at on public.modeles_stock;
create trigger modeles_stock_updated_at
before update on public.modeles_stock
for each row execute function public.update_updated_at();

alter table public.modeles_stock enable row level security;

drop policy if exists modeles_stock_select on public.modeles_stock;
create policy modeles_stock_select on public.modeles_stock
for select to authenticated
using (
  revendeur_id = auth.uid()
  or public.current_user_role() = 'admin'
  or exists (
    select 1
    from public.commandes
    where commandes.modele_stock_id = modeles_stock.id
      and commandes.cordonnier_id = auth.uid()
  )
);

drop policy if exists modeles_stock_insert on public.modeles_stock;
create policy modeles_stock_insert on public.modeles_stock
for insert to authenticated
with check (
  public.is_manager()
  and (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
);

drop policy if exists modeles_stock_update on public.modeles_stock;
create policy modeles_stock_update on public.modeles_stock
for update to authenticated
using (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
with check (revendeur_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists commandes_insert on public.commandes;
create policy commandes_insert on public.commandes
for insert to authenticated
with check (
  public.is_manager()
  and (revendeur_id = auth.uid() or public.current_user_role() = 'admin')
  and exists (
    select 1 from public.clients
    where id = commandes.client_id and (clients.revendeur_id = auth.uid() or public.current_user_role() = 'admin')
  )
  and exists (
    select 1 from public.profiles
    where id = commandes.cordonnier_id and role = 'cordonnier' and is_active = true
  )
  and (
    modele_stock_id is null
    or exists (
      select 1 from public.modeles_stock
      where id = commandes.modele_stock_id
        and (modeles_stock.revendeur_id = auth.uid() or public.current_user_role() = 'admin')
    )
  )
);

create or replace function public.can_access_modele_photo(p_storage_path text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.modeles_stock
    where photo_path = p_storage_path
      and (
        revendeur_id = auth.uid()
        or public.current_user_role() = 'admin'
        or exists (
          select 1
          from public.commandes
          where commandes.modele_stock_id = modeles_stock.id
            and commandes.cordonnier_id = auth.uid()
        )
      )
  );
$$;

grant select, insert, update on public.modeles_stock to authenticated;
grant usage, select on sequence public.modeles_stock_id_seq to authenticated;
revoke execute on function public.can_access_modele_photo(text) from public, anon;
grant execute on function public.can_access_modele_photo(text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'modele-photos',
  'modele-photos',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists modele_photos_select on storage.objects;
create policy modele_photos_select on storage.objects
for select to authenticated
using (
  bucket_id = 'modele-photos'
  and public.can_access_modele_photo(name)
);

drop policy if exists modele_photos_insert on storage.objects;
create policy modele_photos_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'modele-photos'
  and public.is_manager()
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists modele_photos_delete on storage.objects;
create policy modele_photos_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'modele-photos'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.current_user_role() = 'admin'
  )
);
